name: Playwright Tests in Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      # Using Docker-image Playwright
      image: mcr.microsoft.com/playwright:v1.47.2-jammy

    steps:
      # Uploading repository code
      - uses: actions/checkout@v4

      # Installing project dependencies
      - name: Install dependencies
        run: npm ci

      # Running Playwright tests
      - name: Run Playwright tests
        env:
          CI: true
        run: npx playwright test

      # Uploading test results
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
