name: Playwright Tests in Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      # Використання Docker-образу Playwright
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    steps:
      # Завантаження коду репозиторію
      - uses: actions/checkout@v4

      # Встановлення залежностей проекту
      - name: Install dependencies
        run: npm ci

      # Запуск Playwright тестів
      - name: Run Playwright tests
        run: npx playwright test

      # Завантаження звітів про результати тестування
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
